[package]
name = "git-worker"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
host-api = { path = "../host-api" }
serde_json.workspace = true
tokio.workspace = true
